---
title: "TC CSAF Artifact Linkage Concepts Proposal"
author: "Stefan Hagen"
date: "2016-11-26"
output: pdf_document
references:
- id: ODataFAMM2013
  title: Notes on formal aspects common to OASIS OData TC's meeting minutes
  author:
  - family: Hagen
    given: Stefan
  container-title: OASIS Open Data Protocol (OData) TC
  URL: 'http://bit.ly/odata_formal_meeting_minutes_aspects'
  type: article-journal
  version: 1.0
  issued:
    year: 2013
    month: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Proposal - "Artifact Linkage Concepts"

Based on the positive experiences from adherence to artifact linkage concepts e.g. in the OData TC [@ODataFAMM2013], I hereby propose the below artifact linkage concepts to streamline the committee work, maximize transparency and ensure progress for the work products on standards track. The scope of this document encompasses the document describing the issue processing best practices but tries to minimize redundancy where possible. It widens the scope to enable description of artifacts related to TC meetings, meeting minutes, and emails to both public comment and technical committee mailing lists.

## 1. Review of [Action Items](https://www.oasis-open.org/apps/org/workgroup/csaf/members/action_items.php) (AI) and Progress

Action items are referenced by their local ID as generated by the Kavi-Tool upon creation. This ID consists of the constant string **AI#** and an automatically incremented number padded to the left with zeros and to 4 digits like eg. **AI#0123**.

The ownership of action items is noted `[owner: Given Family]` and as indicated by the [AI-List-Tool](https://www.oasis-open.org/apps/org/workgroup/csaf/members/action_items.php). Additionally the time stamp of retrieval is given in the preamble. The list of open action items (before the meeting) may be documented in an appendix esp. in longer minutes to help the reader foxus on the actual progress being made during the meeting.

## 1.1 Linking to AI progression sections in meeting minutes

The linkage to the documentation of an action items specific state progression inside meeting minutes SHOULD be provided through a publicly accessible URL of the meeting minutes. To ease the navigation for the reader this link MAY have a fractional part which is the **lowercased** action items ID where the **'#'sign has of course been stripped**. For meeting minutes this fractional target is guaranteed to point to the relevant subsection of the minutes.

As an example, for linking the action item **AI#0000** to its state progression (from '**Opened** (Note: Due 2016–11–16)' to '**Ongoing** (Note: Due 2013–11–23)') during meeting#1 the specific public URL is (fractional part='ai0000'):

[https://www.oasis-open.org/committees/download.php/59394/csaf-minutes-20161116%2Bmeeting.1.html#ai0000](https://www.oasis-open.org/committees/download.php/59394/csaf-minutes-20161116%2Bmeeting.1.html#ai0000)

## 2 Review of [Issues List](https://issues.oasis-open.org/secure/IssueNavigator.jspa?mode=hide&requestId=13270) (IL) and Progress

Issues are referenced by their local ID as generated by JIRA upon creation. This ID consists of the constant string **CSAF-** and an automatically incremented number like eg. **CSAF-123**. The list of processed issues may be documented in an appendix esp. in longer minutes to help the reader focus on the actual progress being made during the meeting and as a navigational support. If such an index is provided, it will have at most two main parts: First come the public comments (if any), second the JIRA issues. Each list of issues is sorted by ascending issue number. Noted are the ID, the summary and the reference to the relevant subsection where the issue progression has been documented.
 
### 2.1 Notation of Issue State Progressions during Meetings

We minute an issue state progression as an ordered triple consisting of:

1. The initial issue summary (including its status **before** the meeting)
2. Discussion content and decisions i.e. **formally required motion text** potentially _overriding a proposed solution (of the issue's instance in JIRA)_ at the time of the meeting.
3. The resulting issue summary (including its updated status _plus eventual modifications linking to the motion text_  **after** the meeting)

The rationale behind this is: a) to **document the initial status** - _which may well deviate from the (tentative) status set inside the instance in JIRA at that time_, b) to **optimize the transfer of changes resulting from the discussion back into the issue's instance inside JIRA** (if dictated by the accepted motion) and last but not least c) to **ease the lookup** for the reader.

The value of the main status is one (_and only one_) from the set (**New**, **Open**, **Deferred**, **Proposed**, **Resolved**, **Applied** or **Closed**) as documented in "[Best Practices for Issue Handling](http://bit.ly/csaf_best_pract_issues_r1)", where the states and transitions are further explained as they have been adopted by the TC.

A step by step recipe on how to apply these resolutions to new revisions of work products is given in "[How to Apply Resolved Issues](https://www.oasis-open.org/committees/download.php/47018/How%20to%20Apply%20Resolved%20Issues.docx)" and shall assist the editors performing the many formally necessary (but often _purely mechanical_) steps needing attention along the way.

### 2.2 Lifecycle of 'Mainstream' Issues

For the purpose of this section any issue that results in an implemented change will be considered a 'mainstream' issue. The typical lifecycle of such an issue and with focus on the relation between actions, status and documentation in meeting minutes may be illustrated as:
 
1. Created as **New** by Reporter -> **New** [+ Comments]
2. [optional as step 2] The **Proposed** flag can be set during **New** discussions to indicate that the issues' proposal is ready for resolution. _If and only if this is the case, then the steps labelled 3 and 4 may be skipped. In all other cases the step labelled 4 will be mandatory_.
3. Accepted as **Open** by TC -> **Open** [+ Discussions [+ Motion [+ Amendment] ] ]
4. [optional as step 4, but mandatory as status] The **Proposed** flag can be set during **Open** discussions to indicate that a proposal is ready for resolution. _Only ready to implemented proposals will be resolved by the TC_.
5. **Resolved** as Proposed by TC -> **Resolved**
6. Implementation during work phase visible to the editor.
7. Signalled as **Applied** by Editor -> **Applied** [+ Discussions [+ Motion [+ Amendment] ] ] 
8. **Closed** as Applied by TC -> **Closed**

The relation of incoming and outgoind issues states is further listed and explained in the following subsection. Any remaining details on available issue states and transitions may be found in "[Best Practices for Issue Handling](http://bit.ly/csaf_best_pract_issues_r1)".

#### 2.2.1 Relation of Incoming and Outgoing Issue States

The issues that are put on a TC meeting agenda MUST have one of the three following  incoming states: 

1. **New+Proposed** 
2. **Open+Proposed** 
3. **Applied** 

For each of those incoming issue states, the corresponding possible outgoing states - amended with explanations (_noted in parentheses_) - are:

1. Incoming state: **New+Proposed** implies the possible outgoing states: 
    1. **New+Proposed** (_TC did not act on this_), 
    2. **Open+Proposed** (_TC agreed to open but has not resolved yet_), 
    3. **New** (_TC removed the issue from Proposed since the proposal was not complete_), 
    4. **Open** (_TC accepted the issue but  removed the issue from Proposed since the proposal was not complete_), 
    5. **Resolved** (_successfully resolved_), 
    6. **Closed** (_TC closed issue with no further action_).
2. Incoming state: **Open+Proposed** implies the possible outgoing states: 
    1. **Open+Proposed** (_TC did not act on this_), 
    2. **Open** (_TC accepted the issue but  removed the issue from Proposed since the proposal was not complete_), 
    3. **Resolved** (_successfully resolved_), 
    4. **Closed** (_TC closed issue with no further action_).
3. Incoming state: **Applied** implies the possible outgoing states: 
    1. **Resolved** (_if the TC disagrees with the application of the resolution_), 
    2. **Closed** (_TC agrees with the application of the resolution_).
 
 
## 2.3 Linking from JIRA issues to state progression sections in meeting minutes

The linkage from the representation of an issue as noted in JIRA to the documentation of its specific state progression inside meeting minutes SHOULD be provided through a publicly accessible URL of the meeting minutes. To ease the navigation for the reader this link MAY have a fractional part which is the **lowercased** issues ID. For meeting minutes this fractional target is guaranteed to point to the relevant subsection of the minutes.

As a fictive example, for linking the issue **CSAF-42** to its state progression (from **New** to **New+Proposed**) during meeting#123 the specific public URL is (fractional part='csaf-42'):

[https://www.oasis-open.org/committees/download.php/deadbeef/csaf-meeting-123_on-20171231-minutes.html#csaf-42](https://www.oasis-open.org/committees/download.php/deadbeef/csaf-meeting-123_on-20171231-minutes.html#csaf-42)

The corresponding private URL (only visible to TC members) would be:

[https://www.oasis-open.org/apps/org/workgroup/csaf/download.php/deadbeef/latest/csaf-meeting-123_on-20171231-minutes.html#csaf-42](https://www.oasis-open.org/apps/org/workgroup/csaf/download.php/deadbeef/latest/csaf-meeting-123_on-20171231-minutes.html#csaf-42)  

As we tend to keep the filenames persistent, one can usually build the public from the private URL by

1. replacing 'apps/org/workgroup/csaf/' with 'committees/' and
2. removing 'latest/'

Thereby we maximize the public navigation experience throughout our documentation.

## 2.4 Issues related to Public Comments

If an issue created in JIRA is related to a public comment (eg. because it has been accepted as an issue by the TC) the subject of the JIRA issue should follow the format as described in section [[3.2][ci_indicator]].

##3 Notation of Public Comments and Relations to Minutes and Issues [pcnotation]

Public comments are referenced by their local ID pair as generated by the OASIS mailing list archiver upon receipt. The derived ID consists of the string literal **c** the 'YYYYMM' string from the year month folder, the string literal **e** and automatically incremented number padded to the left with zeros and to 5 digits like eg. **c201611e00001**.

## 3.1 Linking from Public Comments to processing sections in meeting minutes

Abiding the rules of OASIS all comments are acknowledged and considered. So every comment received through the single entry point **csaf-comment** will be reflected in one or more meeting minutes.

The linkage from the representation of received comment as noted in the public comment archive rooted at [https://lists.oasis-open.org/archives/csaf-comment/](https://lists.oasis-open.org/archives/csaf-comment/) to the documentation of its specific processing inside meeting minutes SHOULD be provided through a publicly accessible URL of the meeting minutes. To ease the navigation for the reader this link MAY have a fractional part which is the derived ID as described in section [[3][pcnotation]]. For meeting minutes this fractional target is guaranteed to point to the relevant subsection of the minutes.

## 3.2 Linking from Issues to Public Comments [ci_indicator]

If a comment results in an issue created in JIRA the subject of the issue should indicate this by appending the string literal **(public comment $ceID)** with $ceID being replaced with the commentEntryID as described in section [[3][pcnotation]] (cf. [[sample][ci_sample]] below).

It is also beneficial, if the description of the JIRA issue starts with text following the pattern:

    The public comment 
    [$ceID](https://lists.oasis-open.org/archives/csaf-comment/$yearMonth/msg$entryID.html) 
    with title "$subjectOrTitle" indicates, ...
 
with: 

* $ceID being replaced with the commentEntryID as described in section [[3][pcnotation]] 
* $yearMonth replaced with the matching Year-Month folder part of the URL path
* $entryID replaced with the corresponding entry ID
* $subjectOrTitle replaced with the subject of the mail or a title as suggested by the TC (eg. edit for readability, typos etc.)

## 3.2.1 Sample for Comment Linkage Notation in Issues [ci_sample]

As a ficitve sample, the first comment received, could result in issue [csaf-987](https://tools.oasis-open.org/issues/browse/CSAF-987) with the summary:

"Enhance description of normalization procedures (public comment c201611e00000)" 

and the description:

"The public comment [c201301e00001](https://lists.oasis-open.org/archives/csaf-comment/201611/msg00000.html) with title "Invented Title from Subject" indicates, that the description of normalization procedures in the key Construction Rules can be enhanced.".
