<csaf-instance>:
  # ...
  product_tree:
    # ...
    relationships:
    - # <relationship-instance>:
      category: String.Enum
      full_product_name: $defs.full_product_name_t
      product_reference: $defs.product_id_t
      relates_to_product_reference: $defs.product_id_t
    # ...
  # ...
