name: CPE Dictionary Test (CSAF 2.1)

on:
  push:
    paths:
      - 'csaf_2.1/**'
  pull_request:
    paths:
      - 'csaf_2.1/**'

jobs:
  cpe-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Perform CPE Dictionary Test
      run: ./csaf_2.1/test/cpe/run_dictionary_tests.sh
    - name: Perform CPE local examples Test
      run: ./csaf_2.1/test/cpe/run_local_tests.sh
