name: CSAF Mandatory Tests (CSAF 2.1)

on:
  push:
    paths:
      - 'csaf_2.1/**'
  pull_request:
    paths:
      - 'csaf_2.1/**'

jobs:
  mandatory-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Setup Node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: '24'
    - name: Setup csaf-validator-lib
      run: |
        cd ..
        git clone https://github.com/secvisogram/csaf-validator-lib.git
        npm install -g peggy
        cd csaf-validator-lib && npm ci --omit=dev
    - name: Run mandatory tests on examples
      run:  |
        for i in `ls -1 ../csaf/csaf_2.1/examples/csaf/*.json | grep -Ev 'rhsa-2019_1862.json|rhsa-2021_5186.json|rhsa-2021_5217|rhsa-2022_0011.json|cisco-sa-20180328-smi2.json'`
        do
          printf "%s%s\n" "Starting test of " $i
          ../csaf-validator-lib/scripts/runTest.js -f $i -t base -c 2.1
        done
    # Only temporary until examples in the repo are reorganized
    - name: Run mandatory tests on examples/csaf_vex
      run:  |
        for i in `ls -1 ../csaf/csaf_2.1/examples/csaf/csaf_vex/*.json`
        do
          printf "%s%s\n" "Starting test of " $i
          ../csaf-validator-lib/scripts/runTest.js -f $i -t base -c 2.1
        done
    # Commented out as not yet supported by the test tools
    # Only temporary until examples in the repo are reorganized
    #- name: Run mandatory tests on examples/appendix
    #  run:  |
    #    for i in `ls -1 ../csaf/csaf_2.1/examples/csaf/appendix/*.json`
    #    do
    #      printf "%s%s\n" "Starting test of " $i
    #      ../csaf-validator-lib/scripts/runTest.js -f $i -t base -c 2.1
    #    done
